# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[metadata.heroku]
  root-package = "github.com/mappcpd/web-services"
  go-version = "1.9"
  install = [ "./cmd/..." ]

[[constraint]]
  branch = "master"
  name = "github.com/34South/envr"

[[constraint]]
  name = "github.com/algolia/algoliasearch-client-go"
  version = "2.22.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.26"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/graphql-go/graphql"
  version = "0.7.5"

[[constraint]]
  name = "github.com/graphql-go/handler"
  version = "0.2.1"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.3.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.13.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
